### ISSUE TITLE
Error while building 

### ISSUE THREAD

**Issue by EndLess728** [terra-money/react-native-mnemonic-key#10]
I am facing error while compiling the code. I have made new project and installed this library .

```
error: Error: Unable to resolve module events from /Users/ios/Desktop/demo_tests/mnemenic_sample/node_modules/@terra-money/terra.js/dist/client/WebSocketClient.js: events could not be found within the project or in these directories:
  node_modules/@terra-money/terra.js/node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  31 | Object.defineProperty(exports, "__esModule", { value: true });
  32 | exports.WebSocketClient = void 0;
> 33 | var events_1 = require("events");
     |                         ^
  34 | var ws_1 = __importDefault(require("ws"));
  35 | var hash_1 = require("../util/hash");
  36 | var escapeSingleQuotes = function (str) { return str.replace(/'/g, "\\'"); };
    at ModuleResolver.resolveDependency (/Users/ios/Desktop/demo_tests/mnemenic_sample/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (/Users/ios/Desktop/demo_tests/mnemenic_sample/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/Users/ios/Desktop/demo_tests/mnemenic_sample/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/ios/Desktop/demo_tests/mnemenic_sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/ios/Desktop/demo_tests/mnemenic_sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/ios/Desktop/demo_tests/mnemenic_sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/ios/Desktop/demo_tests/mnemenic_sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/ios/Desktop/demo_tests/mnemenic_sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)

```

**Comment by hanjukim** [comment]
@EndLess728 can you try to add events module manually?

**Comment by EndLess728** [comment]
I tried adding `events` and then I got some other missing packages errors which I manually installed. below is the list of packages I have manually installed. 

```
events
stream
buffer
```

But I got the new error

```
 LOG  Running "mnemenic_sample" with {"rootTag":1,"initialProps":{}}
 WARN  Possible Unhandled Promise Rejection (id: 0):
ReferenceError: Can't find variable: Buffer
create$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:107278:36
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:23453:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:23623:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:23453:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:23525:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:23535:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:28138:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:28239:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:28655:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:28694:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:28912:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:3080:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:2858:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:3063:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.mnemenic-sample:2857:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
```

**Comment by azerpas** [comment]
Same issue
```
error: Error: Unable to resolve module stream from ...../node_modules/cipher-base/index.js: stream could not be found within the project or in these directories:
  node_modules
  ../../node_modules
```

**Comment by diegodelrieu** [comment]
Hi, has this been resolved ?

**Comment by azerpas** [comment]
> Hi, has this been resolved ?

Check this https://github.com/terra-money/react-native-mnemonic-key/pull/15
